name: Deploy to Dev Server

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npx vite build --config vite.config.static.ts
        
      - name: Deploy to dev server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_LOGIN }}
          password: ${{ secrets.DEPLOY_PASS }}
          port: 22
          script: |
            # Create backup of current dev site
            if [ -d "public_html_dev_backup" ]; then
              rm -rf public_html_dev_backup
            fi
            if [ -d "public_html_dev" ]; then
              cp -r public_html_dev public_html_dev_backup
            fi
            # Create directory if it doesn't exist
            mkdir -p magerovska.com/dev
            # Clear current dev site files
            rm -rf magerovska.com/dev/*
            
      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_LOGIN }}
          password: ${{ secrets.DEPLOY_PASS }}
          port: 22
          source: './dist/*'
          target: './magerovska.com/dev/'
          strip_components: 1
